### ISSUE TITLE
Versioning ideas

### ISSUE THREAD

**Issue by vvanholl** [vvanholl/elasticsearch-prometheus-exporter#139]
Hi all,

I 'd like to have ideas about improving versioning management.

**Actually this is a painfull process :**
3 branches : master (6.x) 5.x and 2.x increasing the latest version

**Each time a new ES version is released :** 
- I change the version in gradle.properties to (6.5.0.0 for instance)
- I commit, push and let the CI build and publish artifacts
- I change again version in gradle.properties to 6.5.0.1-SNAPSHOT, commit and push

**There are a lot of drawbacks**
- Too many actions with possible errors
- Difficulties to release again a past version in order to fix a bug
- Backporting new features and bug fixes are impossible

I have thoughts about creating a branch for each ES version. I think this could manage some situations but I am not yet fully convinced.

What do you think about that ? Do you have any advice ?

Thank you

**Comment by vvanholl** [comment]
@lukas-vlcek

**Comment by lukas-vlcek** [comment]
# Elasticsearch (plugin) branching model

After spending some time thinking about this I suggest we _learn from_ and _lean towards_ Elasticsearch's model. The reason is this is an Elasticsearch plugin and it has to follow the same release cycle; at the same time we will need to be able to make fixes & features back-ports for older ES releases. First, let's see how Elaticsearch does it.

All the official Elasticsearch plugins are part of the main repo at [elasticsearch/plugins](https://github.com/elastic/elasticsearch/tree/master/plugins) and thus are sharing common branching and versioning model following [MAJOR.MINOR.PATCH semantic versioning](https://semver.org/#summary) schema. 

### Elasticsearch creates branches at the **MAJOR.MINOR** level

Taking into account primarily official release branches we can see the following picture:

<table>
<tr>
  <th colspan="7">Elasticsearch branches</th>
</tr>
<tr>
	<th>Purpose</th>
   <th colspan="6">Name</th>
</tr>
<tr>
	<td><i>development</i></td>
	<td><code>master</code></td>
	<td colspan="5"></td>
</tr>
<tr>
	<td><i>release 6.x</i></td>
	<td><code>6.x</code></td>
	<td><code>6.0</code></td>
	<td><code>6.1</code></td>
	<td>...</td>
	<td><code>6.5</code></td>
	<td>TBD</td>
</tr>
<tr>
	<td><i>release 5.x</i></td>
	<td>n/a</td>
	<td><code>5.0</code></td>
	<td><code>5.1</code></td>
	<td>...</td>
	<td><code>5.5</code></td>
	<td><code>5.6</code></td>
</tr>
</table>

In general, all the new features go into `master` branch first and those that are applicable to 6.x series are brought into `6.x` branch as well which is eventually used to spin new 6.x branches. The branch `6.x` can also receive its own bug-fixing commits (these do not go into `master` at all).

### Each branch gets tags at the **MAJOR.MINOR.PATCH** level when new releases are created from it

Until the first 7.0.0 release is cut the `5.6` branch could be used to create a new branch for next `5.7` release (there is no `5.x` branch because this version is EOL except for the lastest `5.6` branch). For more details check [Maintenance Tables](https://www.elastic.co/support/eol).

This means that at any given point in time mostly 2 branches are being activaly maintained: `master` and `6.x` (ie. _future_ and _current_ release).

This would explain why Elastic [instruct contributors](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#submitting-your-changes) to submit PR agains fresh `master` branch only. It seems they do not officialy provide instructions on how to submit PRs against older versions/branches. I think they will handle that on an individual case base and they will probably handle back-porting these changes to all relevant release branches themselves. However, this situation should be rare thanks to general [EOL policy](https://www.elastic.co/support/eol), but it happens ([here](https://github.com/elastic/elasticsearch/pull/35827) is one example of fix commit that went directly to `6.x` branch and can not be found in `master`).

One obvious implication of this model is that making an extra bug-fix release of individual plugin only is not possible. Instead a new release of whole stack will be cut.

I seems to me that primary approach of moving commits between maintained branches is via `git cherry-pick` and solving code conflicts if needed. There are some blog posts explaining this model:

- [Git process that works - say no to GitFlow](https://reallifeprogramming.com/git-process-that-works-say-no-to-gitflow-50bf2038ccf7) (_~ Marek Piechut_)
- [Release Strategies](https://www.renemoser.net/blog/2016/01/09/release-strategies/) (_~ René Moser_)

This means that all applicable commits have to be selected manually (unless some additional tooling is used as suggested in <https://arxiv.org/pdf/1708.02393.pdf>). This also means that use of other mechanisms is highly desired to minimize possible human errors - such as **extensive automated testing** and **release process automation**.

## Community Elasticsearch plugin

Unlike Elasticsearch any community or third-party ES plugin needs to be able to deliver bug-fix releases for any released Elasticsearch version. This imply we will need to create a new branch for each official Elasticsearch release at the **MAJOR.MINOR.PATCH** level. Fortunatelly, we already use appropriate semantic versioning schema.

<table>
  <tr>
    <th>Branch</th>
    <th>Release tags</th>
  </tr>
  <tr>
    <td><code>5.6.1</code></td>
    <td><code>5.6.1.0</code> &rarr; <code>5.6.1.1</code> &rarr; <code><b>5.6.1.2</b></code></td>
  </tr>
  <tr>
    <td><code>5.6.0</code></td>
    <td><code>5.6.0.0</code> &rarr; <code><b>5.6.0.1</b></code></td>
  </tr>
</table>

This will lead to significant number of branches. Let's see some numbers:

```
# Assuming we are in <elasticsearch_root>
# Unique tags per major ES release:    Count:
$ git tag | grep v2 | wc -l            25
$ git tag | grep v5 | wc -l            41
$ git tag | grep v6 | wc -l            27
```

<p align="center"><a href="https://learnaboutgmp.com/good-manufacturing-practices-cgmp/the-top-7-how-to-reduce-manufacturing-human-error/"><img src="https://learnaboutgmp.com/wp-content/uploads/2018/05/Untitled7.png" width="350"></a></p>

This can easily grow to 100 and more branches going forward. I was quickly searching the web if there are any restrictions on GitHub or known issues with high number of branches but did not find anything. 

### How to get there

To follow this model we will need to create all those branches (fortunatelly, this can and **should be automated**, see below). Fortunatelly, none of our existing branches will clash with new branches so we should be ok without danger of crewing up public commit history too much.

I need to think about how to populate branches for existing plugin releases correctly. For example, we will have branch `2.4.5` and we will need to get in all relevant commits with tags `2.4.5.0` and `2.4.5.1` in correct order. I think we should be able to populate all branches for existing releases without changing single commit hash, meaning all past released artifacts should be still valid. This will be a lot of fun...

### Other things to do

- **Document contribution best practices**<br>
It is important to make sure commits are well made so that they can be easily cherry picked. See the blogs mentioned above. Also Elastic mention contributions are [squashed before merging](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#submitting-your-changes) via GitHub.

- **Value automated testing**<br>
We already started implementing integration tests. We should continue this effort and add tests for exisitng funtionality as well. There might be some challenges back-porting these for Elasticsearch 2.x. But I think I contributed some integration tests for 2.x in the past so there is an working example of what we can use...

- **Document release process**<br>
It must be documented what needs to be done in order to:

  - release next version
  - release fix or feature back-port for older version

- **Automate release process**<br>
It is vital to automate as much as possible:

  - GitHub allows for [automatically created releases](https://help.github.com/articles/creating-releases/#automatically-creating-releases). This means we can provide a script that calls GitHub APIs to [Create a release](https://developer.github.com/v3/repos/releases/#create-a-release).

**Comment by lukas-vlcek** [comment]
//ping @jprante
Jörg, I was thinking you might provide valuable input here, you are/were maintaining a lot of native ES plugins. Given we need to be able to do bug-fixes and feature back-ports do you think there is _easier_ way going forward than starting a branch for each ES release (i.e. at the "major.minor.patch" level of ES) and on that branch adding plugin releases at "major.minor.patch.plugin_release" level?

**Comment by lukas-vlcek** [comment]
@vvanholl PTAL at https://github.com/lukas-vlcek/elasticsearch-prometheus-exporter-branches-switch
Please see the README for use explanation. Let me know what you think.

**Comment by jprante** [comment]
@lukas-vlcek thanks for pinging me.

Yes, I also struggled at maintaining major version branches (2.x, 5.x, 6.x) and having to prepare plugin versions manually. I know the pain of delivering compatible plugin versions for each and every Elasticsearch version, down to the patch level. In short, I gave up. I decided to pick once or twice a year a selected version for my internal projects, paying the price to skip latest versions and falling behind.

That said, I would not start new branches on major.minor.patch level. The major or major.minor level looks fine.

To make life easier, I collected all my plugins into one "super plugin". A large codebase, and it comes with drawbacks. Right now I'm at 6.3.2 and use a plugin versioning scheme of 6.3.2.x. If I have to branch, I create major.minor branches. 

An automatic method to backport new plugin features to older versions is a challenge in my opinion. Changes in ES areas in previous versions (esp. 2.x) were quite unpredictable. 

Side note: for my purpose, ES has a skewed plugin concept. Plugins can be managed at runtime, which might be okay for most users. But my situation is different. I want to extend ES only at build time, adding functionality before packaging a custom ES application, for example, adding dependencies from Maven repos. I don't want others having to modify the ES application by using CLI commands later.

Sorry for being not helpful and bothering you with my irrevelant opinion instead.

**Comment by lukas-vlcek** [comment]
@vvanholl So what do you think? Do you think we can proceed further and accept the new branching model? Or do you think we shall first develop some supporting scripts as suggested above?

Did you have a chance to [check the script](https://github.com/lukas-vlcek/elasticsearch-prometheus-exporter-branches-switch#how-to-use-this-script) that I created to switch to the new model?

**Comment by lukas-vlcek** [comment]
I also suggest to make the README file quite minimal and move as much as possible to Project github pages:
- https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/
- https://pages.github.com/

**Comment by lukas-vlcek** [comment]
I am going to close this ticket. Managing that many branches would be a big pain. We are going to maintain branches for the major ES releases (`6.x`, `5.x`, ...) now. If there is, however, a need to release a fix or upgrade for older release we will handle that individually case by case.

Feedback welcome! We can re-open this ticket again if there is a need.
