### ISSUE TITLE
Export number of read_only_indices

### ISSUE THREAD

**Issue by benjaminjb** [vvanholl/elasticsearch-prometheus-exporter#230]
I'm interested in getting a count of read_only indices in my ES as we get over the flood stage ( https://www.elastic.co/guide/en/elasticsearch/reference/master/disk-allocator.html ). This stat doesn't seem to be exported here, and I was just curious if there was a reason why or if you would welcome a PR for that?

**Comment by lukas-vlcek** [comment]
PRs are always welcome 😃 
Which API exposes the info about index being in read_only mode?

**Comment by Battleroid** [comment]
Looking at this a bit. Looks like `GetSettingsReponse` would provide it?

Would have to supply the request portion with the correct `IndiciesOptions` so that wildcards for `_all` work and such, and use the option that ignores unavailable indices.

https://github.com/elastic/elasticsearch/blob/v7.5.0/server/src/main/java/org/elasticsearch/action/admin/indices/settings/get/GetSettingsResponse.java
