### ISSUE TITLE
Live update of export settings doesn't seem to work

### ISSUE THREAD

**Issue by jgoeres** [vvanholl/elasticsearch-prometheus-exporter#282]
Hi,

I tried disabling the index and cluster setting metrics as described by sending a PUT request to
/_cluster/settings with this payload:

    {
      "transient" : { 
        "prometheus.indices" : false,
        "prometheus.cluster.settings" : false
      }
    }
The request was acknowledges, but the metrics starting with es_cluster_* and es_index_* are still there.
What am I doing wrong here?
THX
J

**Comment by lukas-vlcek** [comment]
Hi,

which version do you use?

**Comment by jgoeres** [comment]
Hi, 

I observed this on 7.7.0(.0) but have since updated to ES 7.8.1 and the exporter 7.8.1.0, and there it works as expected.

Regards
J

**Comment by lukas-vlcek** [comment]
That is strange. IIRC we do not explicitly have a test to cover the case when ES node is started with disabled metrics but maybe this can be added now.
IIRC it was hard to figure out how to configure ES testing framework to start node with enabled metrics and then with disabled metrics, but that was some time ago, I hope things have improved since then and it should be possible to implement now.
I am closing the ticket now, please report back if you run into this issue again.
Thanks!
