### ISSUE TITLE
No disk io when use glusterfs

### ISSUE THREAD

**Issue by vinkdong** [vvanholl/elasticsearch-prometheus-exporter#94]
Hi, 
I am using glusterfs to store data on my elasticserach cluster, The disk io is always 0, Is there any metric about glusterfs io and read-write bytes?

**Comment by vvanholl** [comment]
Hi,

I don't think you'll find something relevant about glusterfs in elasticsearch metrics. In fact I think this is because of the nature of the file system which is network oriented.

Maybe you'll have something better using the node_exporter or gluster_exporter :
https://github.com/prometheus/node_exporter
https://github.com/ofesseler/gluster_exporter

Vincent

**Comment by vvanholl** [comment]
By the way, I am curious about your usecase using GlusterFS with ElasticSearch.
Do you use it for a production environment ?
What are the the performances ?

**Comment by VinkDong** [comment]
@vvanholl Thank you for the reply!
We have start test of GlusterFS but there is something bad and make elasticsearch status to red easily.
